{%- extends 'hide.tpl' -%}
{%- block body -%}
{%- set internals = ["metadata", "output_extension", "inlining", 
                    "raw_mimetypes", "global_content_filter"] -%}
---
{%- for k in resources |reject("in", internals) %}
{{ k }}: {{ resources[k] }}
{%- endfor %}
---

<!--
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: {{ resources.nb_path }}
-->

<div class="container" id="notebook-container">
        {% raw -%}
           {% if page.badges or page.badges == nil %}
           <div class="pb-5 d-flex flex-wrap flex-justify-end">
                {% include notebook_github_link.html %}{% include notebook_colab_link.html %}
           </div>
           {% endif -%}

           {%- if page.toc %}
                {% toc %}
           {% endif %}
        {%- endraw %}
        {{ super()  }}
</div>
{%- endblock body %}